# fly.toml app configuration file generated for fso-part11-bloglist-with-ci-cd-thrumming-fog-8382 on 2025-04-26T13:11:14+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fso-part11-bloglist-with-ci-cd-thrumming-fog-8382'
primary_region = 'arn'

[build]

[deploy]
  strategy = 'canary'

[env]
  PORT = '3000'

[processes]
  app = 'node index.js'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/api/health'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
